#!/bin/bash

echo "🧪 TESTING WISHLIST FEATURE - COMPLETE"
echo "======================================"
echo ""

# Check servers
echo "📡 1. Checking servers..."
SERVER_RUNNING=false
CLIENT_RUNNING=false

if lsof -i :5000 >/dev/null 2>&1; then
  echo "   ✅ Server is running (port 5000)"
  SERVER_RUNNING=true
else
  echo "   ❌ Server NOT running - please start it!"
  echo "      cd server && npm start"
fi

if lsof -i :3000 >/dev/null 2>&1; then
  echo "   ✅ Client is running (port 3000)"
  CLIENT_RUNNING=true
else
  echo "   ❌ Client NOT running - please start it!"
  echo "      cd client && npm start"
fi

if [ "$SERVER_RUNNING" = false ] || [ "$CLIENT_RUNNING" = false ]; then
  echo ""
  echo "⚠️  Please start both servers before testing!"
  exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 WISHLIST FEATURE TEST CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Backend Changes:"
echo "   • User model: wishList uses ObjectId refs"
echo "   • User route: PATCH /user/:userId/:listingId"
echo "   • Toggle logic: Add/Remove based on existence"
echo ""
echo "✅ Frontend Changes:"
echo "   • ListingCard: Fixed wishlist logic"
echo "   • WishList page: Auto-refresh with useMemo"
echo "   • Redux: setWishList action"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 TEST SCENARIOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test 1: ADD to Wishlist (from Home Page)"
echo "  1. Go to http://localhost:3000"
echo "  2. Login if not already"
echo "  3. Find a listing (not yours)"
echo "  4. Click heart icon ❤️ (white)"
echo "  Expected:"
echo "    ✓ Heart turns RED"
echo "    ✓ Console: '🔄 Adding to wishlist...'"
echo "    ✓ Console: '✅ Added to wishlist'"
echo ""
echo "Test 2: REMOVE from Wishlist (from Home Page)"
echo "  1. On a listing with RED heart"
echo "  2. Click heart icon ❤️ (red)"
echo "  Expected:"
echo "    ✓ Heart turns WHITE"
echo "    ✓ Console: '🔄 Removing from wishlist...'"
echo "    ✓ Console: '✅ Removed from wishlist'"
echo ""
echo "Test 3: VIEW Wishlist Page"
echo "  1. Click avatar → 'Wish List'"
echo "  2. Or go to: http://localhost:3000/{userId}/wishlist"
echo "  Expected:"
echo "    ✓ See all saved listings"
echo "    ✓ Console: '📋 Fetching details for X wishlist items...'"
echo "    ✓ Console: '✅ Successfully loaded X wishlist items'"
echo ""
echo "Test 4: REMOVE from Wishlist Page"
echo "  1. On Wishlist page"
echo "  2. Click heart ❤️ on any listing"
echo "  Expected:"
echo "    ✓ Listing disappears immediately"
echo "    ✓ Console: '✅ Removed from wishlist'"
echo "    ✓ Console: '🔄 WishList changed, re-fetching...'"
echo "    ✓ Page auto-refreshes"
echo ""
echo "Test 5: Cannot Add Own Listing"
echo "  1. Find your own listing"
echo "  2. Try to click heart ❤️"
echo "  Expected:"
echo "    ✓ Console: '⚠️ Cannot add own listing to wishlist'"
echo "    ✓ Heart stays WHITE"
echo "    ✓ No change"
echo ""
echo "Test 6: Must Be Logged In"
echo "  1. Logout"
echo "  2. Try to click heart ❤️"
echo "  Expected:"
echo "    ✓ Button is disabled (grayed out)"
echo "    ✓ Cannot click"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 DEBUGGING TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open DevTools (F12):"
echo ""
echo "1. Console Tab:"
echo "   Look for these messages:"
echo "   • '🔄 Adding to wishlist...' or '🔄 Removing from wishlist...'"
echo "   • '✅ Added to wishlist' or '✅ Removed from wishlist'"
echo "   • '📋 Fetching details for X wishlist items...'"
echo "   • '✅ Successfully loaded X wishlist items'"
echo ""
echo "2. Network Tab:"
echo "   Check for:"
echo "   • PATCH request to /user/{userId}/{listingId}"
echo "   • Status: 200 OK"
echo "   • Response: { message: '...', wishList: [...] }"
echo ""
echo "3. Redux DevTools:"
echo "   Check:"
echo "   • Action: user/setWishList"
echo "   • Payload: Array of listing IDs"
echo "   • State: user.wishList updated"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ COMMON ISSUES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Issue: Heart doesn't change color"
echo "  • Check: User logged in?"
echo "  • Check: Console for errors"
echo "  • Check: Network tab - API call successful?"
echo "  • Fix: Clear cache, hard refresh (Cmd+Shift+R)"
echo ""
echo "Issue: 'Creator information not available'"
echo "  • This should ONLY appear when ADDING (not removing)"
echo "  • Check: Is it a new listing without creator?"
echo "  • Fix: Ensure listing has creator field populated"
echo ""
echo "Issue: Wishlist page doesn't update"
echo "  • Check: Redux DevTools - wishList updated?"
echo "  • Check: Console - '🔄 WishList changed' message?"
echo "  • Fix: Restart client, clear cache"
echo ""
echo "Issue: Can't remove from wishlist page"
echo "  • Check: Console for errors"
echo "  • Check: Network - PATCH request sent?"
echo "  • This was the main bug - should be FIXED now!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "See docs folder for:"
echo "  • WISHLIST_COMPLETE_IMPLEMENTATION.md - Full guide"
echo "  • WISHLIST_FEATURE_FIXED_VI.md - Vietnamese guide"
echo "  • WISHLIST_FAVORITE_BUTTON_FIX.md - Button fix details"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 Ready to test! Open http://localhost:3000 and try it out!"
echo ""
echo "Good luck! 🍀"
echo ""

